resilience4j.circuitbreaker:
instances:
  backendA:
    registerHealthIndicator: true
    slidingWindowSize: 4
    failureRateThreshold: 50
  backendB:
    registerHealthIndicator: true
    slidingWindowSize: 10
    permittedNumberOfCallsInHalfOpenState: 3
    slidingWindowType: TIME_BASED
    minimumNumberOfCalls: 20
    waitDurationInOpenState: 50s
    failureRateThreshold: 50
    eventConsumerBufferSize: 10
    recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
